### ISSUE TITLE
[BUG] Experience report

### ISSUE THREAD

**Issue by daniel-vainsencher** [quarylabs/quary#10]
Whether this is a bug or multiple or not a bug is arguably subjective, but I wanted to tried to give quary a chance and didn't do so great due to multiple paper cuts and uncertainties, and I thought it might be useful to you as an outsider's perspective.

I have done a bunch of data work, but haven't used dbt before either, which might explain some of the issues or not.

TL;DR: I tried all three ways to try out quary, only the command line worked, and that can easily be made much better.

#### First blood

Initially I tried to just use the tool from the command line and rely on its internal documentation + https://github.com/quarylabs/quary/.

- First thing I tried after deciding to give it a shot is `cargo install quary`, and was surprised to find it not published.
- Next I started from the current repo, which offered installs either through brew or the vscode extension. 
- I don't love vscode, so first I tried `cargo build --release`. That didn't work.
- I looked at the subcrates and guessed `cargo install --path rust/cli` would be it, that worked (after updating to latest stable rust).
- Not sure where to go from there, I tried `quary --help`.

    - "a very fast and useful database tool" doesn't tell me what it does. Very fast at deleting DBs? ;)
    - After trying a few different things, I came back and tried `quary init`, which filled my directory with what looks like a complete small project based on the template. This is pretty nice, actually, better than what I did before, which was to clone the template myself. The reason I didn't try this first is because the help doesn't explain that's what it does. In my experience most tools with an `init`, like `git init`, create a valid but empty project. The help entry of "Initialize a new project in the current directory" could have turned out to be either.
    - Once in the template project, I was not quite sure what to do. 

        - compile? what even  needs compilation? 

            - after running this tells me it processed 10 models and 65 tests and completed successfully. 
            - It does not seem to have affected my template directory at all, which makes me wonder where the outputs of compilation went. 
            - I'm guessing that we are using an in memory sqlite DB for everything, therefore no trace is left of the compile, but I'm only guessing that because I peeked at the quary.yaml. 
            - Will that be a problem later because everything we built is gone? or will later steps invoke compile anyway if needed, so I didn't need to run compile at all in the first place? No idea.

        - build? "build the seed and model views". 

            - The seed seems to be csv files, what there needs building? maybe in other cases seeds are sometimes views?
            - The output is very terse, just progress bar that immediately goes to 29. No idea 29 what. Would be nicer if it looked more like the output to compile, at least when passed `--verbose`.
        - test? sounds good.
            - Have to admit I initially ran it without -s, which failed with an error that a table is missing, which was pretty opaque at that time.
            - After looking again at https://github.com/quarylabs/quary/, I saw the `-s` and that passed the tests. 
            - I am now speculating that because we're using an in memory DB, the views are missing, so we need to "Rather than running the tests against the views,s run them against the source tables by building the model in CTEs". 
            - Note that if I had read that help about `-s` before knowing about the in memory db thing, I would not have had an idea that that will solve my problem, this issue is not mentioned in the internal or repo help.
            - While I'm following the repo README, I see `quary run`, try it, and it is unrecognized.

So at this point, I think using the command line might work, I can't rely on internal documentation to get along. That's ok, gotta start somewhere. Maybe I should be using the vscode extension anyway?

#### VSCode...

- So I fired up VSCode on my machine, opened a project folder, got the recommendation to install the extension, agreed, tried to run some Quary commands and...
- Got a lot of "initializing extensions" that didn't go anywhere.
- Killed VSCode, brought it back up on the folder, tried again, and immediately got an option to "sign in to quary". 

    - Wait, why do I need to sign in to Quary? Almost no extensions need a login. What is the sign in for exactly? what information  will be sent to quary? Hmm, its not explained before the login prompt, not a great vibe, but let's try to find out.
    - https://github.com/quarylabs/template/tree/main doesn't mention the signin at all.
    - The extension documentation says: "Open the Sample Project: Access our template repository in GitHub's VSCode instance with no account required." so no explanation of what happens when one does sign in, which is a bit off putting.
    - Just looking at the command palette, it looks like there are a lot of options there, so maybe the command line version is going to be a pretty limited way of using quary?
    - https://www.quary.dev/ does not answer this :/
    - https://www.quary.dev/docs/documentation/installation doesn't mention an account being required either.
    - Ok... let's trust it. Tried to sign it, it sends me at a website I do not recognize, shows me a code and asks to confirm I see it in extension authenticator, but I see no such code in vscode at all. Eventually it times out.
    - I give up on that.

#### VSCode on web

- OK, this won't depend on specifics of my PC, let's try it!
- Click the link to https://github.dev/quarylabs/template/blob/main/models/shifts_summary.sql
- Get a github.dev workspace, looks promising, until I try to run a command, wherein sign in again doesn't work: now every time I try to run a command, the Welcome tab reopens blank.

### Expected Behavior:

- `cargo install quary` works, and `quary help` is enough to get an idea how it works as a system.
- vscode extension installation works, and then commands immediately work. If a signin is required, I know what functionality that serves and what terms  it commits me to.
- web demo... just works, unless microsoft is again messing with firefox users.

### Steps To Reproduce:

See above

### Environment:

- OS: PopOS which is approximately Ubuntu 22.04

### Anything else:

I know this is a pre-release, so these are just the kinds of problems it is useful to catch. I don't know enough about your strategy to know whether using the open source part would be reasonable for me, but look forward to learning more.

**Comment by louisjoecodes** [comment]
Hey Daniel! Thank you so much for the feedback. We're sorry you have had this experience we will get back to you on all of the points in a moment.

**Comment by louisjoecodes** [comment]
Hello Daniel, 

Thank you for taking the time to try out Quary and for sharing your detailed feedback with us. We highly value insights from data experts like yourself! Based on your comments, we've made several improvements in the latest release to address the issues you encountered:

# 1. Installation Enhancements

We explored the possibility of distributing Quary via the Cargo package manager. However, due to the lengthy compilation time required for each installation (a few minutes), we concluded that this would not provide an optimal user experience. This is partly because Quary is designed to support multiple databases, each requiring a substantial number of dependencies.

Instead, we've directed our releases to this repository. You can now easily install our CLI directly from the [latest releases](https://github.com/quarylabs/quary/releases/latest).

# 2. CLI documentation Improvements

We have refined our CLI documentation for greater clarity:

```quary init```: This command creates a starter project, which is a deviation from the traditional 'init' command found in most CLIs. We've made this distinction clear in our documentation.

```quary compile```: This command validates the project structure and model references without interacting with the database. It ensures that all references within the models are correct and will throw an error if any discrepancies are found.

```quary test:```: As you rightly pointed out, this command runs tests either against the 'built' models created by Quary or alternatively with the `-s` flat set against the source tables.

```quary build```: This is the 'deployment' command that executes the models created in the project into the target database. In the case of your experience, these models would then be present in the SQLite database.

Here's an overview of our enhanced CLI documentation, which is now included in the latest release:
```
A tool for managing SQL transformations and tests. For more documentation on these commands, visit: [quary.dev/docs](http://quary.dev/docs)
Usage: quary [OPTIONS] <COMMAND>
Commands:
  init                                Initialize demo project with sample seeds & models inside current directory
  compile                       Validate the project structure and model references without database
  build                            Build and execute the model views/seeds against target database
  test                              Run defined tests against target database
  convert-dbt-project  Convert a dbt core project to a quary project and place in the specified path
  help                             Print this message or the help of the given subcommand(s)
Options:
  -p, --project-file <PROJECT_FILE>  Project file location [default: quary.yaml]
  -h, --help                                              Print help
  -V, --version                                         Print version
```

# 3. Signing in to the extension

The first time you use the Quary extension, you'll be prompted to sign in. This is to provide you with an integrated experience. We collect some telemetry on the commands executed to track feature usage, which helps us prioritize future developments. We've updated our extension sign-in page to include a link to our [privacy policy](https://www.quary.dev/legal/privacy), which outlines the data we collect.

# 4. Compatibility with Firefox

We've noted the issue with Firefox displaying a blank page when a command is run without authentication. As a temporary workaround, you can bypass this by running the `CTRL + SHIFT + P` > `Quary: Sign in` command in VSCode. This process should work smoothly in Chrome and Safari. We've [raised a ticket with Microsoft](https://github.com/microsoft/vscode/issues/206661) to address this issue further.

Thanks again for taking the time to use Quary and for providing us with valuable feedback. Feel free to reach out at any point or raise another issue in case we can improve your experience.

**Comment by daniel-vainsencher** [comment]
Sounds like you've addressed quite a few of the issues, I'll try to give it another shot in the next few days.

**Comment by louisjoecodes** [comment]
Thanks Daniel, looking forward to hearing your feedback! Will keep this issue open so we can keep track of anything you come across.

**Comment by louisjoecodes** [comment]
Closing issue, feel free to re-open if there is anything else!
