### ISSUE TITLE
[BUG] cached files causing errors

### ISSUE THREAD

**Issue by lockmeister** [quarylabs/quary#225]
### Current Behavior:

after editing tables_metadata.sql, and running `quary compile` and `quary build`, I get errors relating to my previous version of tables_metadata.sql.
I can't see how to clear a cache or start again.

UNLESS this is a problem related to the fact that I have read-only access to the database?

### Expected Behavior:

execution of `quary compile` and `quary build` should reference current files

### Environment:

VScode, WSL

**Comment by benfdking** [comment]
Hey @lockmeister, not quite sure what is going on here. I do think though it is because of the access requirements you have.  `compile` and the `build` steps do require the ability to list tables/views in the analytics schema, so my guess is that is the problem you are facing. 

This is good feedback and we'll include some more colour in the guide.

**Comment by louisjoecodes** [comment]
Thank you for raising this issue and apologies for the confusion. I think the errors you are seeing are likely due to read-only access to the database, rather than an issue with Quary itself.

To clarify:
```quary compile``` does not use any caching. Its purpose is to parse and validate the project configuration, models and sources. It does not execute any queries against the database.

```quary build``` executes the SQL queries defined in your models against the target database to materialize them as tables/views. This requires appropriate database permissions.

Since you have read-only access, ```quary build``` is unable to create the required tables/views in your analytics schema. We'll update our guide to make these distinctions clearer. 

If you send me the error message you are getting, I'd be happy to help you set the database up with the correct permissions.

Please let us know if you have any other questions!

**Comment by louisjoecodes** [comment]
Documentation updated - resolving issue for now,  please feel free to re-open with any further questions.
