### ISSUE TITLE
[BUG] Build accesses internet: Failure: the server hosted at that remote is unavailable

### ISSUE THREAD

**Issue by yurivict** [quarylabs/quary#236]
### Current Behavior:

Build shouldn't access internet. All files should be pre-downloaded.
But quary build attempts to download something:
```
buf generate
Failure: the server hosted at that remote is unavailable.
*** Error code 1
```

How to pre-download the files that it attempts to download?

### Environment:

- OS: FreeBSD 14.0

### Anything else:

For security reason most reasonable porting/packaging systems disallow internet access during package build.

**Comment by benfdking** [comment]
Hey 👋

Thanks for bringing this to our attention! Very helpful. 

The proto files weren't committed due to some hacks we put in place for some moving of code. Those are now committed and the build is now more deterministic.

All You should need to build the binary is now 'cargo'. Cargo will of course need access to pull dependencies but hopefully that's understandable!

Let us know if that helps!

**Comment by yurivict** [comment]
The latest master revision still has the same problem.

**Comment by benfdking** [comment]
Sorry I should have specified ... 🤦 You don't need to run `buf` anymore to build the binary,

**Comment by yurivict** [comment]
It builds now.
Thank you!
